CREATE TABLE Users
(
	TelegramId BIGINT NOT NULL PRIMARY KEY,
	CWLogin VARCHAR(100) NOT NULL,
	Rank INTEGER NULL,
	Honor INTEGER NULL,
	TotalTasks INTEGER NULL,
	LastUpdate DATETIME NULL,
	ChatId BIGINT NOT NULL,
	Color VARCHAR(9) NOT NULL DEFAULT '#ff000000'
);

CREATE TABLE ChartMessages
(
	ChatId BIGINT NOT NULL PRIMARY KEY,
	MessageId BIGINT NOT NULL
);